### ISSUE TITLE
Minor Improvements

### ISSUE THREAD

**Issue by rennaMAhcuS** [kingmk-3/LS_crypto#1]
The `project.py` program is functioning as expected, but some minor changes are suggested:

- To make the input process much easier, ask for the `key` every time you are asked for the `case 1` as it is not useful for the `case 2` and `case 3`, instead of asking to change it or not every time.

> [!NOTE]
> This is a minor suggestion from my side 🙂.

**Mohana, CSeC CTM**

**Comment by rennaMAhcuS** [comment]
Also, `case 3` is taking a lot of time for some cases. You can try to improve the logic also...

**Comment by kingmk-3** [comment]
I will look into it. Thanks.

**Comment by rennaMAhcuS** [comment]
Sure. I am closing this issue.
